class ApplicationController < ActionController::API

  def encode_token(payload)
    JWT.encode(payload, 'my_secret')
    # USE A BETTER SECRET
    # encode method is provided by jwt gem, used to generate token
    # "The method encode provided by the JWT gem will be utilized to generate a token. JWT.encode takes two arguments, the payload object and a string that represents a “secret”. The method encode_token will return the token generated by JWT."
  end
  
end
